### ISSUE TITLE
Please provide reproducible builds

### ISSUE THREAD

**Issue by Giszmo** [melis-wallet/melis-cm-client#1]
I tried to reproduce your latest release on Google Play (v1.5.40) but failed so far. I failed to find the correct revision but also had issues compiling the project with the given build instructions. [Here](https://walletscrutiny.com/posts/io.melis.clientwallet/) you can find all the steps I tried to compile the app.

**Comment by ghost** [comment]
The missing package `ember-leaf-theme-basic` contains the themed css and graphic assets, and can be downloaded  from the releases page at 

https://github.com/melis-wallet/melis-cm-client/releases

It just need to be unpacked on the same level folder as the cloned repository.

The `README` file has been updated, too.

**Comment by Giszmo** [comment]
Why would you not add the assets to the repository? Anyway, if it is a pre-build step to download and unpack some files, this should be documented in a way that it can be automated.

**Comment by Giszmo** [comment]
So ... please update your build instructions. It took me a lot of guessing to figure out what to do with the ember-leaf-theme-basic-master-9601b6f57e468dd0ccc4bbcdb01ae1aebfb0153c.zip. How about adding it as a submodule? 

`git submodule add https://github.com/melis-wallet/ember-leaf-theme-basic`

Then, to get to the right version of the folder users could just run `git submodule update --init --recursive` and would get the folder re-instantiated.

Anyway, looking forward to reproducing the build. I updated the [review on walletscrutiny](https://walletscrutiny.com/posts/io.melis.clientwallet/).

**Comment by lele-melis** [comment]
We have published a snapshot of the current 1.6.18 release, which is the release currently deployed as the web application at wallet.melis.io.
the `release-1.6.5` branch contains a snapshot for the mobile/desktop applications, for reference. It's a couple of minor bugfixes behind  and some documentation.

**Comment by emanuelb** [comment]
They released code for version 1.6.15 on google-play but with some stuff missing, see: https://github.com/melis-wallet/melis-cm-client/issues/2#issuecomment-823414740

>  The release-1.6.5 branch contains a snapshot of the version used for the mobile/desktop applications, for reference. It's a couple of minor bugfixes behind and some documentation.

will try to reproduce soon and edit this reply with results.

**Comment by ghost** [comment]
The 1.6.18 (and 1.6.15) code that we released yesterday has no "stuff" missing. Everything we use to build the web, android and iOS application is included.
Note that 1.6.18 has a better and more detailed build documentation, and there are a couple of scripts and fixes that make the build easier. You can easily diff the two versions and see they differ only by a few lines fixing a minor bug (other than said docs/scripts).

**Comment by emanuelb** [comment]
> It's a couple of minor bugfixes behind 
> You can easily diff the two versions and see they differ only by a few lines fixing a minor bug 

That's what I meant by "stuff missing".

> You can easily diff the two versions

I am still unable to compile the apk from source-code of 1.6.15 branch, the review at walletscrutiny shows FTBFS (fail to build from source), and currently it's the same for me, will open soon issues with build failures I am encountering from Containerfile I writing in order to compile apk, and other issues found during the process and looking at related files to build process.

**Comment by emanuelb** [comment]
The comment here show how to build the app & diff from production release, app not reproducible yet, there are several diffs:
https://github.com/melis-wallet/melis-cm-client/issues/5#issuecomment-847093436

**Comment by emanuelb** [comment]
Source code is missing for the latest release 1.6.24, opened issue about it: #14 @lele-melis Please publish source code of the latest release
